server:
  port: 10011

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/auditingdb
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: AUDITING-SERVICE
#  config:
#    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
kafka:
  bootstrap-servers: localhost:29092
  consumer:
    group-id: auditing-poc-consumer
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      specific.avro.reader: true
      auto.offset.reset: earliest # used in this case for testing in this poc
      #schema.registry.url: http://localhost:8079
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicNameStrategy
      value.subject.topic.name.format: "audit-data-topic2-value"
  schema.registry.url: http://localhost:8079


# Logging configuration
logging:
  level:
    root: INFO
    com.tudux.kafkamicros: INFO

topics:
  consumer-topic: "audit-data-topic2"
